---
# tasks file for mytomrole
- name: install tomcat
  yum:
   name: tomcat
   state: present

- name:  copy tom config file into all nodes
  template:
    src:  templates/mytomconfig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat

- name:  Install Admin Packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps

- name: coy tom user file into all nodes
  template:
    src: templates/mytomusers.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat

- name: i want to deploy maha java war file into webapps 
  get_url:
    url: http://52.90.17.232:8081/artifactory/ravipem2/5/target/raviLogin-1.0.war
    dest: /usr/share/tomcat/webapps/raviLogin-1.0.war
    force_basic_auth: yes