---
# tasks file for mytomrole
- name: install tomcat
  apt:
    name: tomcat7
    state: present

- name:  copy my tom config file into nodes
  template:
    src: templates/mytomconfig.j2
    dest: /etc/default/tomcat7
  notify: restarttomcat

- name: install admin packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples

- name: copy tomuser file into nodes 
  template:
    src: templates/mytomusers.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: restarttomcat

- name: i want to deploy ravi java war file into webapps  
  get_url:
    url: http://54.145.225.65:8081/artifactory/ravianskey/4/target/raviLogin-1.0.war
    dest: /var/lib/tomcat7/webapps/raviLogin-1.0.war
    force_basic_auth: yes